### ISSUE TITLE
Where is special version of py2exe located?

### ISSUE THREAD

**Issue by mgraf2** [mitre/caldera-agent#2]
I do not see a special version of py2exe included with this, where is it located?

**Comment by dm-mitre** [comment]
https://github.com/mitre/caldera-py2exe

We also have precompiled versions of this available at https://github.com/mitre/caldera-agent/releases

**Comment by dm-mitre** [comment]
I have updated the readme to link to py2exe in 8d3d3de67480a54e62a5184cb1a893c98b5c1310
