### ISSUE TITLE
Training: Second task in user training flag is not clearing

### ISSUE THREAD

**Issue by mohdalnahel** [mitre/caldera-agent#6]
The second task in the user training requires deploying a remote agent. I deployed the agent successfuly but the flag is not marked as completed and I can't proceed to the next task. I am using caldera for my MSc project and I need to get this done so can anyone please help me.

**Comment by nopfor** [comment]
Is the second agent deployed on a different OS than the first?

Is the first agent still running?

**Comment by mohdalnahel** [comment]
Th operating system was the problem. The server was running on a kali linux and the remote system was centos7 but when I ran the agent on windows it was marked as completed. I guess it is not just a different OS it requires a differenr Platform. Thanks b17zr this was very helpful.
